name: CI Frontend (UI)

on: [push]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs:
  ui-frontend:
    name: CI Frontend (UI)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Code Linting
        run: npm run lint

      - name: Unit Testing
        run: npm test

      - name: Code Building
        run: npm run build
